export const data = [
    {
        "id": 1,
        "id_usuario": 101,
        "prioridad": 1,
        "id_unidad_medida": 3,
        "descripcion_solicitud": "Compra de toner para impresora láser",
        "justificacion_solicitud": "Sin insumos para impresión de reportes",
        "cantidad": 4,
        "id_estatus_solicitud": 1,
        "fecha_solicitud": "2025-05-26T09:00:00Z",
        "id_tipo": 2,
        "id_categoria": 5,
        "id_grupo_articulo": 12,
        "descripcion_requerimiento": "Toner HP 30A negro",
        "marca": "HP",
        "modelo": "30A",
        "observaciones": "Entrega urgente solicitada",
        "archivo_adjunto": "toner_hp_especificaciones.pdf",
        "created_at": "2025-05-26T09:00:00Z",
        "updated_at": "2025-05-26T09:00:00Z"
    },
    {
        "id": 2,
        "id_usuario": 104,
        "prioridad": 2,
        "id_unidad_medida": 1,
        "descripcion_solicitud": "Compra de sillas ergonómicas",
        "justificacion_solicitud": "Mejorar condiciones ergonómicas del personal",
        "cantidad": 10,
        "id_estatus_solicitud": 1,
        "fecha_solicitud": "2025-05-25T15:30:00Z",
        "id_tipo": 1,
        "id_categoria": 3,
        "id_grupo_articulo": 7,
        "descripcion_requerimiento": "Sillas con soporte lumbar y brazos ajustables",
        "marca": "ErgoStyle",
        "modelo": "ES-100",
        "observaciones": "Preferencia color negro",
        "archivo_adjunto": null,
        "created_at": "2025-05-25T15:30:00Z",
        "updated_at": "2025-05-25T15:30:00Z"
    },
    {
        "id": 3,
        "id_usuario": 109,
        "prioridad": 3,
        "id_unidad_medida": 2,
        "descripcion_solicitud": "Adquisición de licencias Microsoft Office",
        "justificacion_solicitud": "Requerido para operación administrativa",
        "cantidad": 5,
        "id_estatus_solicitud": 2,
        "fecha_solicitud": "2025-05-20T11:15:00Z",
        "id_tipo": 3,
        "id_categoria": 8,
        "id_grupo_articulo": 21,
        "descripcion_requerimiento": "Licencias anuales de Office 365 Business",
        "marca": "Microsoft",
        "modelo": "Office 365 Business",
        "observaciones": "Incluya soporte técnico",
        "archivo_adjunto": "licencias_office_requerimiento.pdf",
        "created_at": "2025-05-20T11:15:00Z",
        "updated_at": "2025-05-20T11:15:00Z"
    },
    {
        "id": 4,
        "id_usuario": 110,
        "prioridad": 1,
        "id_unidad_medida": 1,
        "descripcion_solicitud": "Compra de papel bond tamaño carta",
        "justificacion_solicitud": "Reabastecer oficina",
        "cantidad": 50,
        "id_estatus_solicitud": 1,
        "fecha_solicitud": "2025-05-19T10:00:00Z",
        "id_tipo": 2,
        "id_categoria": 4,
        "id_grupo_articulo": 9,
        "descripcion_requerimiento": "Resma de papel blanco de 75g",
        "marca": "Scribe",
        "modelo": "Bond-75",
        "observaciones": null,
        "archivo_adjunto": null,
        "created_at": "2025-05-19T10:00:00Z",
        "updated_at": "2025-05-19T10:00:00Z"
    },
    {
        "id": 5,
        "id_usuario": 102,
        "prioridad": 2,
        "id_unidad_medida": 2,
        "descripcion_solicitud": "Cotización de servidor dedicado",
        "justificacion_solicitud": "Reemplazo de infraestructura antigua",
        "cantidad": 1,
        "id_estatus_solicitud": 2,
        "fecha_solicitud": "2025-05-18T14:45:00Z",
        "id_tipo": 3,
        "id_categoria": 10,
        "id_grupo_articulo": 15,
        "descripcion_requerimiento": "Servidor con 64GB RAM y RAID 10",
        "marca": "Dell",
        "modelo": "PowerEdge R740",
        "observaciones": "Incluir garantía extendida",
        "archivo_adjunto": "specs_server.pdf",
        "created_at": "2025-05-18T14:45:00Z",
        "updated_at": "2025-05-18T14:45:00Z"
    },
    {
        "id": 6,
        "id_usuario": 106,
        "prioridad": 1,
        "id_unidad_medida": 3,
        "descripcion_solicitud": "Compra de mouse ergonómicos",
        "justificacion_solicitud": "Lesiones por uso continuo de mouse tradicional",
        "cantidad": 8,
        "id_estatus_solicitud": 1,
        "fecha_solicitud": "2025-05-17T09:30:00Z",
        "id_tipo": 1,
        "id_categoria": 5,
        "id_grupo_articulo": 6,
        "descripcion_requerimiento": "Mouse vertical ergonómico inalámbrico",
        "marca": "Logitech",
        "modelo": "MX Vertical",
        "observaciones": null,
        "archivo_adjunto": null,
        "created_at": "2025-05-17T09:30:00Z",
        "updated_at": "2025-05-17T09:30:00Z"
    },
    {
        "id": 7,
        "id_usuario": 107,
        "prioridad": 3,
        "id_unidad_medida": 1,
        "descripcion_solicitud": "Compra de botiquín de primeros auxilios",
        "justificacion_solicitud": "Requerimiento de seguridad laboral",
        "cantidad": 2,
        "id_estatus_solicitud": 3,
        "fecha_solicitud": "2025-05-16T13:20:00Z",
        "id_tipo": 2,
        "id_categoria": 6,
        "id_grupo_articulo": 11,
        "descripcion_requerimiento": "Botiquín completo con insumos médicos básicos",
        "marca": "SafeKit",
        "modelo": "SK-100",
        "observaciones": "Ubicar en entradas y comedor",
        "archivo_adjunto": "botiquin_listado.pdf",
        "created_at": "2025-05-16T13:20:00Z",
        "updated_at": "2025-05-16T13:20:00Z"
    },
    {
        "id": 8,
        "id_usuario": 108,
        "prioridad": 2,
        "id_unidad_medida": 2,
        "descripcion_solicitud": "Cotización de impresora multifuncional",
        "justificacion_solicitud": "Centralizar impresiones y escaneos",
        "cantidad": 1,
        "id_estatus_solicitud": 2,
        "fecha_solicitud": "2025-05-15T16:10:00Z",
        "id_tipo": 3,
        "id_categoria": 7,
        "id_grupo_articulo": 13,
        "descripcion_requerimiento": "Impresora multifuncional A3, WiFi",
        "marca": "Brother",
        "modelo": "MFC-J6935DW",
        "observaciones": "Incluir instalación",
        "archivo_adjunto": "impresora_specs.pdf",
        "created_at": "2025-05-15T16:10:00Z",
        "updated_at": "2025-05-15T16:10:00Z"
    },
    {
        "id": 9,
        "id_usuario": 105,
        "prioridad": 1,
        "id_unidad_medida": 1,
        "descripcion_solicitud": "Compra de garrafones de agua",
        "justificacion_solicitud": "Abastecimiento mensual",
        "cantidad": 40,
        "id_estatus_solicitud": 1,
        "fecha_solicitud": "2025-05-14T08:00:00Z",
        "id_tipo": 2,
        "id_categoria": 2,
        "id_grupo_articulo": 3,
        "descripcion_requerimiento": "Garrafón de 20 litros, purificada",
        "marca": "Bonafont",
        "modelo": "20L",
        "observaciones": "Entrega en diferentes pisos",
        "archivo_adjunto": null,
        "created_at": "2025-05-14T08:00:00Z",
        "updated_at": "2025-05-14T08:00:00Z"
    },
    {
        "id": 10,
        "id_usuario": 111,
        "prioridad": 2,
        "id_unidad_medida": 2,
        "descripcion_solicitud": "Contratación de servicio de fumigación",
        "justificacion_solicitud": "Control de plagas trimestral",
        "cantidad": 1,
        "id_estatus_solicitud": 2,
        "fecha_solicitud": "2025-05-13T12:15:00Z",
        "id_tipo": 4,
        "id_categoria": 11,
        "id_grupo_articulo": 20,
        "descripcion_requerimiento": "Fumigación oficinas + bodega",
        "marca": null,
        "modelo": null,
        "observaciones": "Servicio nocturno preferido",
        "archivo_adjunto": "fumigacion_plan.pdf",
        "created_at": "2025-05-13T12:15:00Z",
        "updated_at": "2025-05-13T12:15:00Z"
    }
    // Continúa con más registros si lo deseas
]
